const GET_DATA = 'GET_DATA';
const LOADED = 'LOADED';
const CART_ADD_ITEM = 'CART_ADD_ITEM';
const UPDATE_FILTERS = 'UPDATE_FILTERS';
const CART_REMOVE_ITEM = ' CART_REMOVE_ITEM';
const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';

module.exports = {
  GET_DATA,
  LOADED,
  UPDATE_FILTERS,
  CART_ADD_ITEM,
  CART_REMOVE_ITEM,
  CART_UPDATE_ITEM
}