const GET_DATA = 'GET_DATA';
const LOADED = 'LOADED';
const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
const CART_ADD_ITEM = 'CART_ADD_ITEM';


module.exports = {
  GET_DATA,
  LOADED,
  CHANGE_CATEGORY,
  CART_ADD_ITEM
}